import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../../provider";
import SideNavbar from "../components/SideNavbar";
import Header from "@/components/Header";
import React from "react"; // Import React

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <React.StrictMode>
            {" "}
            
            <>
              {/* <Header /> */}
              <div className="flex w-full">
                <SideNavbar />
                <div className="w-full h-screen overflow-y-scroll bg-slate-50">
                  <main className="w-full  p-4">{children}</main>
                </div>
              </div>
            </>
          </React.StrictMode>
        </body>
      </Providers>
    </html>
  );
}
